[package]
name = "combinatorial-swarmability-demo-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
combinatorial-swarmability-demo-core = { path = "../demo-core" }
serde_json.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true

